# Generated by Django 5.0.14 on 2026-10-01 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_item_item_type_alter_item_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CAMERA", "Camera"),
                    ("RADIO", "Radio"),
                    ("VEHICLE", "Vehicle"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="inventory.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Subcategories",
                "ordering": ["name"],
                "unique_together": {("category", "name")},
            },
        ),
        migrations.CreateModel(
            name="SubSubcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsubcategories",
                        to="inventory.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sub-subcategories",
                "ordering": ["name"],
                "unique_together": {("subcategory", "name")},
            },
        ),
        migrations.AddField(
            model_name="item",
            name="subsubcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="inventory.subsubcategory",
            ),
        ),
    ]
