# Generated by Django 5.0.14 on 2026-10-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_category_alter_item_item_type_subcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
