# Generated by Django 5.0.14 on 2026-10-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_model_catalog"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["model_name", "subsubcategory", "status", "location"],
                name="item_lot_lookup_idx",
            ),
        ),
    ]
